// PROBLEM 2
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms. */

//SOLUTION

var first, second, third, sum = 2;

first = 1;
second = 2;

do {
  third = first + second;
  if (third % 2 === 0) {
    sum = sum + third;
  }
  first = second;
  second = third;
} while (second <= 4000000);

console.log("Sum of the even terms in the Fibonacci sequence(less than 4,000,000) is : " + sum);
